### ISSUE TITLE
board with lr1110-modem cann't joined server

### ISSUE THREAD

**Issue by enddls** [Lora-net/lr1110_modem_application_example#2]
hi

I use my board which updated lr1110-modem.

and I use Loriot server and st gateway(p-nucleo-LRWAN2).

I entered device information(dev_eui, join_eui, appkey) at loriot server.

but my board cann't joined server with lr1110-modem.

how is my board joined loriot server?

thank you

**Comment by matthieuantoine** [comment]
Hello,

Do you have access to the logs of your gateway? Do you see the join request messages sent by the modem?

Thanks.
_Matthieu

**Comment by smtcbboulet** [comment]
Hello,

In the code, did you set the USE_SEMTECH_JOIN_SERVER to 0 ? by default it's set to 1 and doesn't use the appkey entered by the user but the Semtech algorithm derivation key. would you have the log from the device ?

regards,

Ben

**Comment by enddls** [comment]
> 
hello, @matthieuantoine 

> Do you have access to the logs of your gateway? 
=> yes, but log is shown recieved lora rf data. no lan communcation data log.
>
>Do you see the join request messages sent by the modem?
=> I don't know, but data that endnode sent was shown by st gateway log.

thank you.

**Comment by enddls** [comment]
hello, @smtcbboulet 

> did you set the USE_SEMTECH_JOIN_SERVER to 0 ? 
> -Yes, when device_state is DEVICE_STATE_INIT, I set modem_response_code = lr1110_modem_set_app_key( &lr1110, app_key );

> would you have the log from the device ?
> -No, endnode device is not log.

thank you.

**Comment by enddls** [comment]
hello, @matthieuantoine / @smtcbboulet 

I find reason that my board with lr1110-modem cann't be joined server.

I setup mistake my board lr1110-modem so my board with lr1110-modem cann't be joined server.

I setup rightly my board lr1110-modem then my board with lr1110-modem is joined server loriot.

thank you your help.

have a good day.
