### ISSUE TITLE
Application layer clock synchronizations

### ISSUE THREAD

**Issue by gianni2996** [Lora-net/lr1110_modem_application_example#3]
Hi everybody, 
I am using my custom board with LR1110 modem mounted on it. Following this repo I wrote the code to join the network and activate the ALC functionality. The device join successfully the network, than i receive back 3 events of type LR1110_MODEM_LORAWAN_EVENT_NEW_LINK_ADR, but not the one that corresponds to time synchronization (I have activated it and set port 202 for that service). What should be the problem? 
Thanks in advance.

**Comment by smtcbboulet** [comment]
Hello Gianni, sorry for the late answer, do you forward the alc sync request to loracloud once the request in your application server ? the alc_sync is a loracloud service, you must forward the request to loracloud from your application server in order to have the answer to downlink to the device.
regards,
Ben

**Comment by gianni2996** [comment]
Hello, yes I enabled the loracloud integration (also have done the procedure of claim device and i see on the loracloud the last join of the device), in fact every uplink i see also the event "integration" on the device messages, but the synchronization does not occur. I attach two files with lorawan frames and device messages maybe they can help understand what is the problem.


[device_data.txt](https://github.com/Lora-net/lr1110_modem_application_example/files/6537308/device_data.txt)
[lorawan-frames.txt](https://github.com/Lora-net/lr1110_modem_application_example/files/6537310/lorawan-frames.txt)
