### ISSUE TITLE
uart_firmware_update not working with Dev Kit

### ISSUE THREAD

**Issue by sohaibqamar** [Lora-net/lr1110_modem_application_example#5]
Hi, I have built the code with Keil for "uart_firmware_update" as the active target and run it on Nucleo-STM32L467G with the LR1110 Dev kit connected.
I have installed Python 3.10.4 and pyserial 3.5. 
I have tried both using Modem and Transceiver firmware to update it, but both commands give almost the same Error.  I have attached a screenshot of the error. I am resetting Nucleo (LEDs blinking twice) on every attempt as it got stuck and TX Led keeps ON. 
![image](https://user-images.githubusercontent.com/12796461/164872786-b150ce0a-bc66-42c5-a552-29b8b514cd13.png)

How can we check if the LR1110 on the Devkit is working as Transceiver or Modem-E?
Any help would be really appreciated.
Regards.

**Comment by raphui** [comment]
@sohaibqamar Have you found any solution for this issue ?
