### ISSUE TITLE
WiFi Scanning for Country Code

### ISSUE THREAD

**Issue by percz** [Lora-net/lr1110_modem_application_example#6]
There doesn't seem to be a way to extra the country code from the buffer if using the function included in _lr1110_modem_wifi.c_

```
 modem_response_code = lr1110_modem_wifi_search_country_code(
                    context, wifi_settings->channels, wifi_settings->max_results,
                    wifi_settings->nbr_retrials, wifi_settings->timeout, wifi_settings->abort_on_timeout 
                );
```

The only driver function that extracts the country code from the buffer is _lr1110_modem_wifi_read_extended_full_results_
but
_capture_result->nbr_results_ always returns 0, and _capture_result->extended_full_results[i].country_code_ is always empty.

Running the scan command otherwise generates an event, that can be cleared after running the _lr1110_modem_wifi_read_extended_full_results_ function. Suggesting the e-modem firmware is indeed completing a successful scan.

**Comment by MagnusErler** [comment]
@percz Did you find out how to extract the country code?
